### ISSUE TITLE
Database security

### ISSUE THREAD

**Issue by Dzimid** [SergiuszN/lets-discuss#37]
Zabezpieczenie bazy danych, szyfrowanie informacji

**Comment by SergiuszN** [comment]
O jakie zabezpieczenia chodzi, i jakie informacji musimy szyfrować?

**Comment by Dzimid** [comment]
Z tego co pamiętam musimy w szczególny sposób chronić dostępu do bazy danych oraz szyfrować informacje w tabelach, żeby w przypadku włamania nic nie wyciekło w sposób jawny.
