### ISSUE TITLE
Zabezpieczenie przed dodawaniem Managerów z takim samym emailem

### ISSUE THREAD

**Issue by Dzimid** [SergiuszN/lets-discuss#39]
![obraz](https://user-images.githubusercontent.com/14100315/40774585-4821ccdc-64c6-11e8-8787-691fedc325ad.png)

Łapanie tego wyjątku i przerabianie go na stosowny alert

**Comment by Dzimid** [comment]
@SergiuszN 
Do takich pierdułek też robić zadania? (jeżeli nie to usuń to zadanie)

**Comment by SergiuszN** [comment]
Tak niech będzie, to powinno być opracowane i rzucać errorem z powrotem na forme) jako flash message https://symfony.com/doc/2.8/controller.html#flash-messages

**Comment by SergiuszN** [comment]
ale ma bardzo niski priorytet
