### ISSUE TITLE
Utworzyć encji: Company, CompanyWorker, Appraise

### ISSUE THREAD

**Issue by SergiuszN** [SergiuszN/lets-discuss#4]

**Comment by Dzimid** [comment]
@SergiuszN 
Mogę się tym zająć?

**Comment by Dzimid** [comment]
W jaki sposób nazywać branche?

**Comment by SergiuszN** [comment]
Skrót od zadania myślę więc coś w tym stylu: 4-create-entity, gdzie 4 - id zadania
