### ISSUE TITLE
Potwierdzenie usuwania obiektów

### ISSUE THREAD

**Issue by Dzimid** [SergiuszN/lets-discuss#68]

**Comment by Dzimid** [comment]
@SergiuszN Czy taka koncepcja będzie dobra?
![obraz](https://user-images.githubusercontent.com/14100315/41549308-b228e3dc-7325-11e8-8a39-d8f132e4009a.png)

**Comment by SergiuszN** [comment]
wow wow, robisz osobne akcje?

**Comment by SergiuszN** [comment]
a nie watłiej zrobić js + jedna klassa na button, który będzie pobieraw od usera zgodę i submitował formę lub robił redirect?

**Comment by Dzimid** [comment]
Nowych akcji nie dodawałem tylko przerobiłem istniejącą i dodałem nowy widok do usuwania
